### PR TITLE
Remove deprecated asset loader APIs from tests

### PR DESCRIPTION
**Pull request by NolaDonato**
This patch fixes the remaining issues with tests and deprecated asset loader apis. It is required for the tests to run after patch #1184 from GearVRF is applied.

GearVRF DCO signed off by: nola.donato@samsung.com Nola Donato

### CODE REVIEW

**Comment by NolaDonato** [comment]
fixed conflict in picker tests

**Comment by NolaDonato** [comment]
I have reinstated Pull Request #1184 as #1220. This patch depends on that one as Mihail said.

**Comment by liaxim** [comment]
Looks good. Planning to merge Tuesday morning.

**Comment by liaxim** [comment]
@NolaDonato There is merge conflict to resolve.

**Comment by liaxim** [comment]
No longer necessary. Can be closed.

**Pull request closed without merging**
