### PR TITLE
Mesh formats and shader adaptation tests

### PR DESCRIPTION
**Pull request by ragner**
* Mesh formats and shader combination tests
* Shader adaptation tests
* New utils class GVRSceneMaker to create GVRScene from JSON format

We need help with some known issues:

1) Fix for: https://github.com/Samsung/GearVRf/issues/1717 because we have to check material type at our JSON parser.

2) Help to create the right screenshot with the expected results and upload them to github.

3) meshFormatsWithShaderCombinationsTest() : 
    * Screenshot of meshes without textures but with color doesn't work.
    * Help to create the expected screenshots for each combination.

3) meshWithoutLightingTest():
   * GVRf looks not working as expected after add the lighting.

4) meshSwitchTexcoordSet():
   * GVRf looks not working as expected after change the textcoords.

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Cristiano Bozzetto <c.bozzetto@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Eliamara Silva <eliamara.s@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Diego Azulay <diego.a@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
meshStartWithtTextureTest crashes always for me. Probably a gvrf bug.

Golden masters missing. Could you add some for couple of phones?

**Comment by liaxim** [comment]
``obj.getRenderData().getMaterial().setMainTexture(null);`` leads to a crash in gvrf. The null *must* propagate to c++ and the pointer cleared. The Java texture object gets gc-ed (no strong ref to it), takes down the c++ object but we still have a pointer to it in shaderdata.

**Comment by liaxim** [comment]
meshWithoutLightingTest leads to another crash too. Looks like a problem in the https://github.com/Samsung/GearVRf/pull/1737 pull request I am using. Good tests.

**Comment by NolaDonato** [comment]
When I run these tests individually they all work. Running them as a group crashes frequently (I am using PR #1743 to run them)

**Comment by liaxim** [comment]
Planning to merge on Thursday and continue fixing the crashes. There is no fault in the test code from what I can tell. Some of the crashes have been fixed by pending pull requests for the framework.

**Pull request merged**
