### PR TITLE
Let the asset import test compare screenshots

### PR DESCRIPTION
**Pull request by liaxim**

### CODE REVIEW

**Comment by NolaDonato** [comment]
I tested this today with both master and the assimp branch. It does compare all the screen shots now instead of just giving up in the middle.

**Comment by liaxim** [comment]
Sure. I will investigate the tests that hang.

**Comment by liaxim** [comment]
On and off looking at this. For me it never hangs but randomly exits at some time. The tests consume a lot of memory. If they run to completion the total memory usage is over 1GB. Something is leaking a lot.

When the tests just fail, I get a "WIN DEATH" error in logcat and nothing else. I think at some point the OS simply kills the test since there is not enough memory.

**Comment by liaxim** [comment]
Something on the native side is a keeping a reference to OvrViewManager and by proxy to a ton of other stuff. Eliminated the obvious reference in ovr_activity.cpp completely but it didn't help. Quite mysterious.

**Comment by liaxim** [comment]
It was real nasty to find but the global gvrf-context variable we bind for the scripting is being leaked. Presumably somewhere in the scripting libraries we rely upon, something is adding a global reference to the gvr context.

So every time an activity is destroyed, we leak the associated view manager. Since every single test method involves creating a new activity, the framework tests are seriously impacted.

There were some other things but this is the big one. Will keep working on an actual fix.

**Comment by NolaDonato** [comment]
Way to go Mihail! I probably could not have found that in under geologic time. Is this something that could be fixed by switching to V8 or is it unrelated to javascript?

**Comment by liaxim** [comment]
It is caused by the Lua interpreter.

**Pull request merged**
