### PR TITLE
gvr-unittestutils: fix memory leak caused by the concurrent image comparison

### PR DESCRIPTION
**Pull request by liaxim**

### CODE REVIEW

**Comment by liaxim** [comment]
Depends on https://github.com/Samsung/GearVRf/pull/1569

**Comment by liaxim** [comment]
- close streams that were not closed; stream finalizers take care of it but still a good practice

- make the golden bitmap mutable avoiding one bitmap copy; the less bitmaps are used the lower the bitmap leak impact

- eliminate byte[] copy in writeBitmap

- use of static inner classes as a defensive programming practice

**Comment by liaxim** [comment]
Leaked bitmap arrays cause: setPixel and getPixel and android's Bitmap in general is not thread-safe.

**Comment by NolaDonato** [comment]
I did not realize that when I wrote the image compare stuff. Thanks for cleaning it up.

**Comment by liaxim** [comment]
Well, it is my fault really. I made the change to use many worker threads to compare strips of the bitmaps concurrently.

**Comment by liaxim** [comment]
Bitmap-related memory leak fixed by copying pixels to two int[] and using those instead. For the extra memory usage we also gain some additional speed up in the comparison since set/getPixels have more overhead.

**Comment by liaxim** [comment]
With and without this change, most of the picker tests fail.

**Comment by liaxim** [comment]
S6 and S7 run all the tests with memory space to spare.

**Pull request merged**
