### PR TITLE
Mesh picking tests

### PR DESCRIPTION
**Pull request by J0Nreynolds**
Test picking UV coordinates from objects with mesh colliders.

### CODE REVIEW

**Comment by J0Nreynolds** [comment]
@NolaDonato I've added a test for picking BoxColliders, but [this pull request](https://github.com/Samsung/GearVRf/pull/1334) needs to be merged first.

**Comment by J0Nreynolds** [comment]
This can be merged after https://github.com/Samsung/GearVRf/pull/1296.

**Comment by dnvasilev** [comment]
Will be merged soon. @J0Nreynolds , can you create a Vulkan port please?

**Comment by liaxim** [comment]
The tests are crash-prone currently. I think we need to confirm that and figure it out if it is true. What I have observed I put in https://github.com/Samsung/GearVRf/pull/1334.

**Comment by liaxim** [comment]
Planning to merge on Friday.

**Comment by liaxim** [comment]
There can be the odd failed case but much more rare now; on S8 at least. Phones matter since the problems are timing dependent. Looks like the picking event listener never gets called in those cases. Future investigation.

**Pull request merged**
