### PR TITLE
Unit tests from SIDIA

### PR DESCRIPTION
**Pull request by NolaDonato**
These tests compile and build with the latest Framework. The animation tests run until one crashes and then they stop. I wasn't able to run other tests - it seems to only run them if you start the app. Running an individual test does not appear to work.

### CODE REVIEW

**Comment by NolaDonato** [comment]
GearVRF DCO signed off by: nola.donato@samsung.com Nola Donato

**Comment by liaxim** [comment]
Needs rebase

**Comment by NolaDonato** [comment]
I have rebased

**Comment by liaxim** [comment]
Fyi: the build has been updated so if you have the tests repo (using the default name) in the same directory as the framework, build artifacts from the framework build will be automatically copied to GearVRf-Tests/gearvrf-libs/.

Oculus from now on uses the ``backend_oculus-*.aar`` name; the alternative backend will use the generically named ``backend-*.aar``.

**Comment by liaxim** [comment]
I plan to merge this today after lunch. Is that ok?

The GVRAnimationTest fails for me because of a native crash. The gl deleter hack I had to add comes to haunt me. I will fix it after this is merged.

Will make small build tweaks - add the capability to use either oculus or the alternative backend via command line switch. Will add a step that automatically copies oculus signature files if OCULUS_SIGS_DIRECTORY.

**Comment by parthmehta209** [comment]
@liaxim lets hold off on merging. @NolaDonato made some changes to fix/clean up these tests, which is not included in this pull request. Also we need to remove framework-tests/* files from this change.

**Comment by parthmehta209** [comment]
@NolaDonato I have remove the framework-tests/* files from this commit in https://github.com/NolaDonato/GearVRf-Tests/commits/sidiatests3

**Comment by NolaDonato** [comment]
Thank you!

**Comment by NolaDonato** [comment]
Yes, merge it. Several tests fail because of the deleter thing. If you look into the animation test you will find the one that fails is the posteffect animation which asks for the shader  manager. I don’t think the shader manager is ready at the very start…

**Comment by NolaDonato** [comment]
Thanks!

**Comment by liaxim** [comment]
Ok, but this still needs a rebase.

**Comment by NolaDonato** [comment]
I have updated this pull request and rebased from master.

**Comment by NolaDonato** [comment]
it should be ok now, it says there are no conflicts

**Pull request merged**
