### PR TITLE
More performance tests

### PR DESCRIPTION
**Pull request by ragner**
Add more performance tests:

-  multiple shaders using single mesh.
- scene objects with different rendering properties.
- use RGB, RG, GL_RED textures instead of RGBA.
- complex fragment shader
- Modifying mesh data in onStep()

GearVRf-DCO-1.0-Signed-off-by: Eliamara Silva <eliamara.s@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Diego Azulay <diego.a@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>

### CODE REVIEW

**Comment by NolaDonato** [comment]
Please merge with PR #244 and set the expected FPS so the tests pass on GL. I have done this for all the existing tests but not for your new ones.

**Comment by ragner** [comment]
Hi @NolaDonato,
how did you compile the master branch with GL?

**Comment by liaxim** [comment]
@ragner The tests are using the GL renderer by default.

**Comment by liaxim** [comment]
Planning to merge on Wednesday. I think the expected FPS should be phone model-dependent. Currently 55 out 56 tests fail on my S8. These are the numbers I get:

```
02-20 08:00:44.750  3961  3992 E PERFORMANCE: cyl10x10Cubemap FPS = 18.371096
02-20 08:01:24.837  3961  3992 E PERFORMANCE: quad15x15RGB8Bitmap FPS = 17.136003
02-20 08:02:13.219  3961  3992 E PERFORMANCE: cyl10x10R11Bitmap FPS = 14.571241
02-20 08:02:55.874  3961  3992 E PERFORMANCE: cyl10x10CompBmapShareMtl FPS = 16.146395
02-20 08:03:29.311  3961  3992 E PERFORMANCE: quad15x15ShareMtl FPS = 19.193243
02-20 08:04:16.196  3961  3992 E PERFORMANCE: cyl10x10CubemapShareMtl FPS = 14.635218
02-20 08:05:01.617  3961  3992 E PERFORMANCE: quad15x15CubemapShareMtl FPS = 14.002987
02-20 08:05:38.191  3961  3992 E PERFORMANCE: quad15x15 FPS = 17.379215
02-20 08:06:15.320  3961  3992 E PERFORMANCE: cyl10x10RG11BitmapShareAll FPS = 17.024658
02-20 08:06:56.106  3961  3992 E PERFORMANCE: cyl10x10RG11BitmapShareGeo FPS = 15.411882
02-20 08:07:34.029  3961  3992 E PERFORMANCE: quad15x15R11BitmapShareMtll FPS = 16.754160
02-20 08:08:15.860  3961  3992 E PERFORMANCE: cyl10x10ShareMtl FPS = 16.207893
02-20 08:08:49.433  3961  3992 E PERFORMANCE: quad15x15Cubemap FPS = 19.445164
02-20 08:09:28.009  3961  3992 E PERFORMANCE: quad15x15BitmapShareMtl FPS = 16.620958
02-20 08:10:09.683  3961  3992 E PERFORMANCE: quad15x15CompBmapShareMtl FPS = 15.229586
02-20 08:10:55.700  3961  3992 E PERFORMANCE: cyl10x10R11BitmapShareMtll FPS = 14.731518
02-20 08:11:32.646  3961  3992 E PERFORMANCE: cyl10x10R11BitmapShareAll FPS = 17.214666
02-20 08:12:11.630  3961  3992 E PERFORMANCE: cyl10x10R11BitmapShareGeo FPS = 16.230253
02-20 08:12:59.351  3961  3992 E PERFORMANCE: cyl10x10RG11Bitmap FPS = 14.222728
02-20 08:13:35.034  3961  3992 E PERFORMANCE: quad15x15RGB8BitmapShareAll FPS = 17.803099
02-20 08:14:14.562  3961  3992 E PERFORMANCE: quad15x15RGB8BitmapShareGeo FPS = 15.984229
02-20 08:14:56.026  3961  3992 E PERFORMANCE: cyl10x10 FPS = 16.410929
02-20 08:15:41.949  3961  3992 E PERFORMANCE: cyl10x10BitmapShareMtl FPS = 14.949918
02-20 08:16:20.848  3961  3992 E PERFORMANCE: quad15x15RGB8BitmapShareMtll FPS = 16.365273
02-20 08:17:07.110  3961  3992 E PERFORMANCE: cyl10x10RGB8BitmapShareMtll FPS = 14.849279
02-20 08:17:45.417  3961  3992 E PERFORMANCE: cyl10x10BitmapShareGeo FPS = 16.750887
02-20 08:18:22.390  3961  3992 E PERFORMANCE: quad15x15CubemapShareAll FPS = 17.296549
02-20 08:18:54.170  3961  3992 E PERFORMANCE: quad15x15CubemapShareGeo FPS = 20.378359
02-20 08:19:30.461  3961  3992 E PERFORMANCE: cyl10x10RGB8BitmapShareAll FPS = 17.418568
02-20 08:20:08.422  3961  3992 E PERFORMANCE: cyl10x10RGB8BitmapShareGeo FPS = 16.623722
02-20 08:20:46.258  3961  3992 E PERFORMANCE: cyl10x10CubemapShareAll FPS = 16.766802
02-20 08:21:24.273  3961  3992 E PERFORMANCE: cyl10x10CubemapShareGeo FPS = 16.793081
02-20 08:22:01.905  3961  3992 E PERFORMANCE: quad15x15R11BitmapShareAll FPS = 16.777586
02-20 08:22:36.889  3961  3992 E PERFORMANCE: quad15x15R11BitmapShareGeo FPS = 18.321730
02-20 08:23:13.631  3961  3992 E PERFORMANCE: quad15x15Bitmap FPS = 17.494751
02-20 08:24:06.564  3961  3992 E PERFORMANCE: quad15x15RG11Bitmap FPS = 11.843196
02-20 08:24:50.308  3961  3992 E PERFORMANCE: cyl10x10RGB8Bitmap FPS = 15.536394
02-20 08:25:26.751  3961  3992 E PERFORMANCE: cyl10x10ShareAll FPS = 17.404926
02-20 08:26:03.164  3961  3992 E PERFORMANCE: cyl10x10ShareGeo FPS = 17.391808
02-20 08:26:44.635  3961  3992 E PERFORMANCE: quad15x15ShareAll FPS = 15.997867
02-20 08:27:17.481  3961  3992 E PERFORMANCE: quad15x15ShareGeo FPS = 19.480520
02-20 08:28:04.770  3961  3992 E PERFORMANCE: cyl10x10CompBmap FPS = 14.152279
02-20 08:28:43.923  3961  3992 E PERFORMANCE: quad15x15CompBmap FPS = 16.310553
02-20 08:29:27.303  3961  3992 E PERFORMANCE: quad15x15BitmapShareAll FPS = 14.582574
02-20 08:30:05.075  3961  3992 E PERFORMANCE: quad15x15BitmapShareGeo FPS = 16.891891
02-20 08:30:49.157  3961  3992 E PERFORMANCE: cyl10x10Bitmap FPS = 15.680535
02-20 08:31:27.370  3961  3992 E PERFORMANCE: quad15x15RG11BitmapShareMtll FPS = 16.858667
02-20 08:32:12.953  3961  3992 E PERFORMANCE: cyl10x10RG11BitmapShareMtll FPS = 15.066292
02-20 08:32:49.213  3961  3992 E PERFORMANCE: cyl10x10CompBmapShareAll FPS = 17.466232
02-20 08:33:25.853  3961  3992 E PERFORMANCE: cyl10x10CompBmapShareGeo FPS = 17.371666
02-20 08:34:09.124  3961  3992 E PERFORMANCE: quad15x15CompBmapShareAll FPS = 14.523625
02-20 08:34:47.986  3961  3992 E PERFORMANCE: quad15x15CompBmapShareGeo FPS = 16.195206
02-20 08:35:27.653  3961  3992 E PERFORMANCE: quad15x15R11Bitmap FPS = 16.000000
02-20 08:36:12.562  3961  3992 E PERFORMANCE: quad15x15RG11BitmapShareAll FPS = 14.044287
02-20 08:36:54.395  3961  3992 E PERFORMANCE: quad15x15RG11BitmapShareGeo FPS = 15.109544
```

**Comment by NolaDonato** [comment]
We need to look into why the S8 performs so much lower than the S7.

**Comment by liaxim** [comment]
The tests run only slightly faster on Note8, user build.

**Comment by liaxim** [comment]
Btw, these are the numbers for the performance tests on my S7, engineering build. I wouldn't say they are better than S8 or Note8.

```
02-21 17:52:50.195 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10Cubemap FPS = 22.495501
02-21 17:53:35.505 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RGB8Bitmap FPS = 13.903049
02-21 17:54:12.015 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10R11Bitmap FPS = 24.429968
02-21 17:54:57.905 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CompBmapShareMtl FPS = 17.552071
02-21 17:55:45.425 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15ShareMtl FPS = 13.137727
02-21 17:56:38.895 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CubemapShareMtl FPS = 14.562754
02-21 17:57:26.635 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CubemapShareMtl FPS = 13.183336
02-21 17:58:10.945 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15 FPS = 14.092777
02-21 17:58:45.245 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RG11BitmapShareAll FPS = 18.331806
02-21 17:59:08.875 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RG11BitmapShareGeo FPS = 27.453672
02-21 17:59:57.805 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15R11BitmapShareMtll FPS = 12.734797
02-21 18:00:41.565 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10ShareMtl FPS = 18.923862
02-21 18:01:24.945 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15Cubemap FPS = 14.554628
02-21 18:02:14.555 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15BitmapShareMtl FPS = 12.681504
02-21 18:03:03.845 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CompBmapShareMtl FPS = 12.769761
02-21 18:03:40.995 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10R11BitmapShareMtll FPS = 23.630421
02-21 18:04:15.245 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10R11BitmapShareAll FPS = 18.501389
02-21 18:04:37.755 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10R11BitmapShareGeo FPS = 29.020555
02-21 18:05:15.485 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RG11Bitmap FPS = 23.623907
02-21 18:06:02.545 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RGB8BitmapShareAll FPS = 13.255860
02-21 18:06:46.925 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RGB8BitmapShareGeo FPS = 14.067665
02-21 18:07:30.685 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10 FPS = 18.597155
02-21 18:08:08.825 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10BitmapShareMtl FPS = 23.379963
02-21 18:08:58.165 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RGB8BitmapShareMtll FPS = 12.675075
02-21 18:09:35.805 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RGB8BitmapShareMtll FPS = 23.663038
02-21 18:09:58.805 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10BitmapShareGeo FPS = 29.031790
02-21 18:10:44.765 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CubemapShareAll FPS = 13.629858
02-21 18:11:26.405 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CubemapShareGeo FPS = 15.130119
02-21 18:12:00.585 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RGB8BitmapShareAll FPS = 18.334606
02-21 18:12:23.415 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RGB8BitmapShareGeo FPS = 28.643721
02-21 18:13:05.605 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CubemapShareAll FPS = 14.964087
02-21 18:13:48.085 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CubemapShareGeo FPS = 14.881691
02-21 18:14:35.855 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15R11BitmapShareAll FPS = 13.205969
02-21 18:15:20.225 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15R11BitmapShareGeo FPS = 14.122631
02-21 18:16:05.775 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15Bitmap FPS = 13.891140
02-21 18:16:54.045 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RG11Bitmap FPS = 13.073034
02-21 18:17:30.635 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RGB8Bitmap FPS = 24.214052
02-21 18:18:03.965 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10ShareAll FPS = 19.006590
02-21 18:18:36.155 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10ShareGeo FPS = 19.754387
02-21 18:19:23.795 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15ShareAll FPS = 13.677708
02-21 18:20:07.715 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15ShareGeo FPS = 14.162969
02-21 18:20:44.615 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CompBmap FPS = 24.095417
02-21 18:21:29.735 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CompBmap FPS = 13.963881
02-21 18:22:17.665 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15BitmapShareAll FPS = 13.129678
02-21 18:23:02.195 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15BitmapShareGeo FPS = 14.480861
02-21 18:23:39.445 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10Bitmap FPS = 24.404133
02-21 18:24:26.785 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RG11BitmapShareMtll FPS = 13.235683
02-21 18:25:04.325 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10RG11BitmapShareMtll FPS = 23.534027
02-21 18:25:39.135 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CompBmapShareAll FPS = 18.225449
02-21 18:26:13.555 16413-16436/org.gearvrf.tester E/PERFORMANCE: cyl10x10CompBmapShareGeo FPS = 18.439978
02-21 18:27:00.985 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CompBmapShareAll FPS = 13.142331
02-21 18:27:44.685 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15CompBmapShareGeo FPS = 14.462013
02-21 18:28:31.155 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15R11Bitmap FPS = 13.468316
02-21 18:29:16.175 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RG11BitmapShareAll FPS = 13.806116
02-21 18:30:02.675 16413-16436/org.gearvrf.tester E/PERFORMANCE: quad15x15RG11BitmapShareGeo FPS = 13.533326

```

**Comment by liaxim** [comment]
We have @sushantojal to thank for fixing the main performance problem in https://github.com/Samsung/GearVRf/pull/1760. Now the performance tests look much better on S8.

```
cyl10x10Cubemap FPS = 18.371096               cyl10x10Cubemap FPS = 33.873425              
quad15x15RGB8Bitmap FPS = 17.136003           quad15x15RGB8Bitmap FPS = 22.875443
cyl10x10R11Bitmap FPS = 14.571241             cyl10x10R11Bitmap FPS = 33.274178
cyl10x10CompBmapShareMtl FPS = 16.146395      cyl10x10CompBmapShareMtl FPS = 34.748363
quad15x15ShareMtl FPS = 19.193243             quad15x15ShareMtl FPS = 33.814247
cyl10x10CubemapShareMtl FPS = 14.635218       cyl10x10CubemapShareMtl FPS = 30.438313
quad15x15CubemapShareMtl FPS = 14.002987      quad15x15CubemapShareMtl FPS = 24.577070
quad15x15 FPS = 17.379215                     quad15x15 FPS = 34.372135
cyl10x10RG11BitmapShareAll FPS = 17.024658    cyl10x10RG11BitmapShareAll FPS = 32.606922
cyl10x10RG11BitmapShareGeo FPS = 15.411882    cyl10x10RG11BitmapShareGeo FPS = 31.904711
quad15x15R11BitmapShareMtll FPS = 16.754160   quad15x15R11BitmapShareMtll FPS = 29.348465
cyl10x10ShareMtl FPS = 16.207893              cyl10x10ShareMtl FPS = 30.840401
quad15x15Cubemap FPS = 19.445164              quad15x15Cubemap FPS = 31.657257
quad15x15BitmapShareMtl FPS = 16.620958       quad15x15BitmapShareMtl FPS = 29.154518
quad15x15CompBmapShareMtl FPS = 15.229586     quad15x15CompBmapShareMtl FPS = 29.800337
cyl10x10R11BitmapShareMtll FPS = 14.731518    cyl10x10R11BitmapShareMtll FPS = 30.304562
cyl10x10R11BitmapShareAll FPS = 17.214666     cyl10x10R11BitmapShareAll FPS = 32.343269
cyl10x10R11BitmapShareGeo FPS = 16.230253     cyl10x10R11BitmapShareGeo FPS = 33.072430
cyl10x10RG11Bitmap FPS = 14.222728            cyl10x10RG11Bitmap FPS = 29.804779
quad15x15RGB8BitmapShareAll FPS = 17.803099   quad15x15RGB8BitmapShareAll FPS = 30.927835
quad15x15RGB8BitmapShareGeo FPS = 15.984229   quad15x15RGB8BitmapShareGeo FPS = 24.414063
cyl10x10 FPS = 16.410929                      cyl10x10 FPS = 31.392246
cyl10x10BitmapShareMtl FPS = 14.949918        cyl10x10BitmapShareMtl FPS = 30.235840
quad15x15RGB8BitmapShareMtll FPS = 16.365273  quad15x15RGB8BitmapShareMtll FPS = 29.106432
cyl10x10RGB8BitmapShareMtll FPS = 14.849279   cyl10x10RGB8BitmapShareMtll FPS = 30.543678
cyl10x10BitmapShareGeo FPS = 16.750887        cyl10x10BitmapShareGeo FPS = 33.145508
quad15x15CubemapShareAll FPS = 17.296549      quad15x15CubemapShareAll FPS = 29.170111
quad15x15CubemapShareGeo FPS = 20.378359      quad15x15CubemapShareGeo FPS = 29.887920
cyl10x10RGB8BitmapShareAll FPS = 17.418568    cyl10x10RGB8BitmapShareAll FPS = 32.385166
cyl10x10RGB8BitmapShareGeo FPS = 16.623722    cyl10x10RGB8BitmapShareGeo FPS = 33.163830
cyl10x10CubemapShareAll FPS = 16.766802       cyl10x10CubemapShareAll FPS = 31.840374
cyl10x10CubemapShareGeo FPS = 16.793081       cyl10x10CubemapShareGeo FPS = 31.791449
quad15x15R11BitmapShareAll FPS = 16.777586    quad15x15R11BitmapShareAll FPS = 27.623037
quad15x15R11BitmapShareGeo FPS = 18.321730    quad15x15R11BitmapShareGeo FPS = 31.502678
quad15x15Bitmap FPS = 17.494751               quad15x15Bitmap FPS = 29.304029
quad15x15RG11Bitmap FPS = 11.843196           quad15x15RG11Bitmap FPS = 28.340654
cyl10x10RGB8Bitmap FPS = 15.536394            cyl10x10RGB8Bitmap FPS = 30.121994
cyl10x10ShareAll FPS = 17.404926              cyl10x10ShareAll FPS = 32.137119
cyl10x10ShareGeo FPS = 17.391808              cyl10x10ShareGeo FPS = 32.522087
quad15x15ShareAll FPS = 15.997867             quad15x15ShareAll FPS = 35.727047
quad15x15ShareGeo FPS = 19.480520             quad15x15ShareGeo FPS = 36.699493
cyl10x10CompBmap FPS = 14.152279              cyl10x10CompBmap FPS = 27.653593
quad15x15CompBmap FPS = 16.310553             quad15x15CompBmap FPS = 21.099272
quad15x15BitmapShareAll FPS = 14.582574       quad15x15BitmapShareAll FPS = 31.047865
quad15x15BitmapShareGeo FPS = 16.891891       quad15x15BitmapShareGeo FPS = 31.456432
cyl10x10Bitmap FPS = 15.680535                cyl10x10Bitmap FPS = 30.097818
quad15x15RG11BitmapShareMtll FPS = 16.858667  quad15x15RG11BitmapShareMtll FPS = 29.995501
cyl10x10RG11BitmapShareMtll FPS = 15.066292   cyl10x10RG11BitmapShareMtll FPS = 29.707382
cyl10x10CompBmapShareAll FPS = 17.466232      cyl10x10CompBmapShareAll FPS = 32.483353
cyl10x10CompBmapShareGeo FPS = 17.371666      cyl10x10CompBmapShareGeo FPS = 32.159512
quad15x15CompBmapShareAll FPS = 14.523625     quad15x15CompBmapShareAll FPS = 31.384035
quad15x15CompBmapShareGeo FPS = 16.195206     quad15x15CompBmapShareGeo FPS = 28.285875
quad15x15R11Bitmap FPS = 16.000000            quad15x15R11Bitmap FPS = 29.638411
quad15x15RG11BitmapShareAll FPS = 14.044287   quad15x15RG11BitmapShareAll FPS = 25.170952
quad15x15RG11BitmapShareGeo FPS = 15.109544   quad15x15RG11BitmapShareGeo FPS = 28.624588
```

**Pull request merged**
