### PR TITLE
test GVRBillboard

### PR DESCRIPTION
**Pull request by sushantojal**

### CODE REVIEW

**Comment by liaxim** [comment]
Shouldn't the test be more elaborate? Attaching to the camera rig doesn't really exercise the billboard. Probably few quads at some remote x,y,z location would be better. Side-by-side; some with, some without the component.

**Comment by sushantojal** [comment]
Since the quad is offset by some value along the x axis, it doesn't face the camera even if it is a child of the camera rig. It does so only when the billboard component is attached. But yes, should probably have a few more quads to make the test more robust. Will do so.

**Comment by NolaDonato** [comment]
Test multiple camera angles rotating around both X and Y axes, test a camera position other that 0,0,0

**Comment by liaxim** [comment]
Planning to merge as-is. @sushantojal Whenever you get the time, additional tests would be welcome.

**Comment by sushantojal** [comment]
Planning to do it by end of day today.

**Comment by liaxim** [comment]
Looks good to me. Will merge Wednesday.

**Pull request merged**
