### PR TITLE
Adding video tests

### PR DESCRIPTION
**Pull request by NolaDonato**
test mono, horizontal stereo and vertical stereo video playback 
Golden masters in S7Edge and S7Euro dirs.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
testMonoVideoMesh.png is missing

**Comment by liaxim** [comment]
@NolaDonato Should we merge as-is or you will add the missing file first?

**Comment by liaxim** [comment]
Planning to merge on Friday. Will add a golden master later.

**Comment by NolaDonato** [comment]
I have added the golden master

**Pull request merged**
