### PR TITLE
Golden masters for new assimp

### PR DESCRIPTION
**Pull request by NolaDonato**
Light decay changed in latest version of assimp so the lighting tests produce different results now. These are the new golden master images for the lighting tests that changed.

Requires PR #1027

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Says there are conflicts

**Comment by NolaDonato** [comment]
I rebased to remove the conflicts.

**Comment by NolaDonato** [comment]
Please do not merge this one until you merge #1027. These are the images for the correct test results after #1027 is applied.

**Comment by liaxim** [comment]
There are conflicts for real. Needs rebase.

**Comment by NolaDonato** [comment]
I rebased, should be good to go now.

**Pull request merged**
