### PR TITLE
framework-tests: fixes so it compiles

### PR DESCRIPTION
**Pull request by liaxim**
also target api should 22 or less; otherwise the tests will have to ask
for read/write permissions at runtime; try running on a newer phone if
my explanation doesn't make sense

### CODE REVIEW

**Comment by NolaDonato** [comment]
I have tested this pull request and #6 together. I still get the error below if I do not remove the strings.xml file. Is there a better way to fix this problem?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gvr-unittestutils:mergeDebugResources'.
> [string/app_name] D:\projects\android\GearVRf-Tests\gvr-unittestutils\src\main\res\values\strings.xml	[string/app_name] D:\projects\android\GearVRf\GVRf\tools\Framework\demos\gvr-unittestutils\build\generated\res\resValues\debug\values\generated.xml: Error: Duplicate resources

**Comment by NolaDonato** [comment]
These pull requests seem to be incompatible with your earlier fix for this problem:
java.lang.Exception: Custom runner class AndroidJUnit4 should have a public constructor with signature AndroidJUnit4(Class testClass)

**Comment by liaxim** [comment]
Yes, I need to update the two pending pull requests I have. I do not to expect them to work in their current state.

**Comment by NolaDonato** [comment]
I figured out that I need the exgradle-test branch of your repo to make the tests work.

**Comment by liaxim** [comment]
This pull request is obsolete.

Btw, the shadowTests do not compile due to GVRRenderData.setCastShadows missing.

**Pull request closed without merging**
