### PR TITLE
Adding asset loader tests

### PR DESCRIPTION
**Pull request by NolaDonato**
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

Note: one test is commented out until the pull request for the GearVRF change is merged

### CODE REVIEW

**Comment by parthmehta209** [comment]
depends on https://github.com/gearvrf/GearVRf-Tests/pull/12

**Comment by parthmehta209** [comment]
depends on https://github.com/gearvrf/GearVRf-Tests/pull/10.

**Comment by NolaDonato** [comment]
This is rebased, can be merged

**Comment by liaxim** [comment]
Conflicts now. Needs rebase.

**Comment by NolaDonato** [comment]
should be able to merge now

**Pull request merged**
