### PR TITLE
Adding texture switching test

### PR DESCRIPTION
**Pull request by NolaDonato**
This test switches between two texture for 1000 frames. It segfaults somewhere in the middle. This causes X3D scripting of texture animation to crash.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Crash due to a race between setImage/clearData and updateGPU.

**Comment by liaxim** [comment]
There is something off with the whole Texture hierarchy; the fact a Texture may or may not have an image which requires excessive checking for correctness. Theoretically mImage can become nullptr at any time if somebody calls setImage from a random thread and it can be called for any of the derived classes. mImage can be nulllptr because it hasn't ever been set too. mImage is also protected and used directly in a ton of derived classes. I understand Texture&Image closely resemble what goes on at the lower level but may be it should've been represented in a more abstract manner.

**Comment by NolaDonato** [comment]
I am totally open to suggestion here. Maybe we should meet tomorrow to discuss it.

**Comment by liaxim** [comment]
If the split is necessary, for example the base Texture needs to completely control the Image and not let derived classes poke at it from here and there. Derived classes should use some protected API to deal with it. Another thing is to not let creation of a Texture without a valid Image. If the no-image state is by definition no longer possible some things can be simplified. Replacing this split Texture/Image entity with something else is probably not realistic in 4.x timeframe.

**Comment by NolaDonato** [comment]
"Another thing is to not let creation of a Texture without a valid Image."
Unfortunately this is not possible. For bitmap assets, the texture is created first and then the image is loaded and when it is finally ready mImage is set. GVRTexture now does what Future<GVRTexture> used to do as well as holding the texture parameters. In GL, the image and texture parameters are a single data structure. In Vulkan they are completely separate. This is why texture and image were decoupled.

Derived classes need to modify the image because some subclasses of Texture deals with the image differently. For textures based on assets, the image is loaded externally. For external textures and render textures, the image is created when that texture is initialized. Since a RenderTexture can be created outside the GL thread, the image can't be set at initialization.

We could change the API so that once the image is created it can't be changed again. There is really no reason for that to occur.

**Comment by liaxim** [comment]
Now the test passes. Planning to merge on Monday.

**Pull request merged**
