### PR TITLE
Adding renderer performance tests

### PR DESCRIPTION
**Pull request by NolaDonato**
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
There are no changed files in this pull request

**Comment by liaxim** [comment]
Ping. There is nothing in this pull request.

**Comment by NolaDonato** [comment]
Yeah, I am looking for these changes. I thought I committed them but I think they are trapped on my home laptop. I will put something into this pull request tonight when I get home.

**Comment by NolaDonato** [comment]
The tests are there now. All of them run less than 60fps on OpenGL. The tests use either 15 x 15 quads or 10 x 10 cylinders. The quads test draw call overhead. The cylinders are 20K vertices so this should test vertex processing. All of the tests should run on Vulkan.

I will add tests which use light sources later to test shader overhead.

**Comment by liaxim** [comment]
Are the tests supposed to pass? They do not for me.

Also the vrapi change (https://github.com/Samsung/GearVRf/pull/1662) causes a crash after the second test for me. Will investigate.

**Comment by NolaDonato** [comment]
The GL tests run for me except for compressed bitmaps. Vulkan crashes on most of them I added the tests so we could debug these issues.

**Comment by liaxim** [comment]
Planning to merge on Monday. Fyi all the tests fail for me on S8. Maybe I don't run them properly or something but these are the results:
```
01-19 07:07:38.094 31682 31727 E PERFORMANCE: cyl10x10Cubemap FPS = 36.719707
01-19 07:07:59.671 31682 31727 E PERFORMANCE: cyl10x10CompBmapShareMtl FPS = 38.078316
01-19 07:08:27.696 31682 31727 E PERFORMANCE: quad15x15ShareMtl FPS = 25.603823
01-19 07:08:51.880 31682 31727 E PERFORMANCE: cyl10x10CubemapShareMtl FPS = 35.640038
01-19 07:09:17.349 31682 31727 E PERFORMANCE: quad15x15CubemapShareMtl FPS = 27.476301
01-19 07:09:40.761 31682 31727 E PERFORMANCE: quad15x15 FPS = 30.444490
01-19 07:10:04.784 31682 31727 E PERFORMANCE: cyl10x10ShareMtl FPS = 35.073360
01-19 07:10:32.770 31682 31727 E PERFORMANCE: quad15x15Cubemap FPS = 23.808578
01-19 07:11:04.285 31682 31727 E PERFORMANCE: quad15x15BitmapShareMtl FPS = 20.538097
01-19 07:11:28.963 31682 31727 E PERFORMANCE: quad15x15CompBmapShareMtl FPS = 26.406126
01-19 07:11:51.140 31682 31727 E PERFORMANCE: cyl10x10 FPS = 34.498619
01-19 07:12:13.881 31682 31727 E PERFORMANCE: cyl10x10BitmapShareMtl FPS = 33.619095
01-19 07:12:31.993 31682 31727 E PERFORMANCE: cyl10x10BitmapShareGeo FPS = 36.984528
01-19 07:12:54.856 31682 31727 E PERFORMANCE: quad15x15CubemapShareAll FPS = 28.807375
01-19 07:13:16.059 31682 31727 E PERFORMANCE: quad15x15CubemapShareGeo FPS = 31.141329
01-19 07:13:35.013 31682 31727 E PERFORMANCE: cyl10x10CubemapShareAll FPS = 35.083614
01-19 07:13:54.011 31682 31727 E PERFORMANCE: cyl10x10CubemapShareGeo FPS = 34.977264
01-19 07:14:17.651 31682 31727 E PERFORMANCE: quad15x15Bitmap FPS = 27.748232
01-19 07:14:35.783 31682 31727 E PERFORMANCE: cyl10x10ShareAll FPS = 35.818756
01-19 07:14:53.994 31682 31727 E PERFORMANCE: cyl10x10ShareGeo FPS = 35.778175
01-19 07:15:16.124 31682 31727 E PERFORMANCE: quad15x15ShareAll FPS = 31.263027
01-19 07:15:40.038 31682 31727 E PERFORMANCE: quad15x15ShareGeo FPS = 26.804861
01-19 07:16:02.820 31682 31727 E PERFORMANCE: cyl10x10CompBmap FPS = 34.007820
01-19 07:16:28.695 31682 31727 E PERFORMANCE: quad15x15CompBmap FPS = 25.141420
01-19 07:16:52.393 31682 31727 E PERFORMANCE: quad15x15BitmapShareAll FPS = 27.367270
01-19 07:17:17.243 31682 31727 E PERFORMANCE: quad15x15BitmapShareGeo FPS = 26.050713
01-19 07:17:39.570 31682 31727 E PERFORMANCE: cyl10x10Bitmap FPS = 33.884903
01-19 07:17:57.948 31682 31727 E PERFORMANCE: cyl10x10CompBmapShareAll FPS = 35.729172
01-19 07:18:16.309 31682 31727 E PERFORMANCE: cyl10x10CompBmapShareGeo FPS = 35.654861
01-19 07:18:39.514 31682 31727 E PERFORMANCE: quad15x15CompBmapShareAll FPS = 27.634487
01-19 07:19:01.556 31682 31727 E PERFORMANCE: quad15x15CompBmapShareGeo FPS = 29.345592
```

**Pull request merged**
