### PR TITLE
golden masters for s7 and s7 edge euro

### PR DESCRIPTION
**Pull request by sushantojal**
phone models:
 S7 : G930V
S7 edge euro: G935F

### CODE REVIEW

**Comment by NolaDonato** [comment]
Do not merge this PR. Most of the X3D images in it are wrong.

**Comment by sushantojal** [comment]
These images were generated using the master branches of tests and framework.

**Comment by liaxim** [comment]
So are the images wrong or not? If wrong, will there be updates to this pull request or should we close for now?

**Comment by sushantojal** [comment]
Will close this PR for now, will need to take a look why some of these images came out wrong.

**Comment by NolaDonato** [comment]
I figured out why they are wrong and fixed it in the tests.  They need t to be done over

**Pull request closed without merging**
