### PR TITLE
Added documentation to two folders and updated some test cases.

### PR DESCRIPTION
**Pull request by mwitchwilliams**
Documentation for Generate Normals and Touch Sensor folders.  Added and cleaned up a few demo's too.

GearVRf-DCO-1.0-Signed-off-by: Mitch Williams 
m1.williams@partner.samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Any comments. Will merge tomorrow otherwise.

**Comment by thomasflynn** [comment]
x3d files look fine. the docs are encrypted.  if you want, i can merge this and do another pull request with the decrypted docs.

**Comment by thomasflynn** [comment]
correction, i cannot decrypt the documents.  apparently only the original author may decrypt them.  so, mitch, you'll need to do another patchset with the documents decrypted.

**Comment by mwitchwilliams** [comment]
That’s ok.  I had some minor edits to include anyway.

MW

**Comment by liaxim** [comment]
The docx files are still encrypted. Just open them with a hex editor and there is a very recognizable header.

**Comment by mwitchwilliams** [comment]
OK, I think I got it right this time.  - Mitch

**Pull request merged**
