### PR TITLE
Added picking tests, synchronization for asset loading

### PR DESCRIPTION
**Pull request by NolaDonato**
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good to me. Maybe we should merge?

Most tests fail right now for me. Also couple of general notes on TestableMain:

- Do we really need a splash screen? It just delays the execution of the test.
- The first thing onInit should probably do is ``gvrContext.getNextMainScene().getMainCameraRig().setCameraRigType(GVRCameraRig.GVRCameraRigType.Freeze.ID);``

**Comment by NolaDonato** [comment]
I would be happy to get rid of the splash screen. How do I do it?

**Comment by liaxim** [comment]
Add this to TestableMain:

```
    public SplashMode getSplashMode() {
        return SplashMode.NONE;
    }
```

Also getNextMainScene() must be changed to getMainScene() after this change.

**Comment by NolaDonato** [comment]
I have updated this pull request to use the gvr-unittestutils library. It now depends on PR #12

**Comment by liaxim** [comment]
Needs rebase

**Pull request closed without merging**
