### PR TITLE
Fixed the picking tests

### PR DESCRIPTION
**Pull request by rahul27**
Freeze the camera rig so that the hit positions are accurate
and predictable.

Fixed hit values from int to float

Also corrected expected values

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
@NolaDonato ?

**Comment by NolaDonato** [comment]
I suggest you put scene.getMainCameraRig().setCameraRigType(GVRCameraRig.GVRCameraRigType.Freeze.ID);

into GVRTestableMain.onInit so the camera will be frozen for all the tests. I was doing this by putting a special file on the phone but your way is much better.

**Comment by NolaDonato** [comment]
Please comment out the canPickWithObject test, GVRObjectPicker is merged now.

**Comment by NolaDonato** [comment]
I have tested this patch with GearVRf PR #891 - it works to fix the problem with pickSceneObjects.

**Comment by rahul27** [comment]
I had no idea about this special file on the phone. Was wondering how you managed to test without the frozen camera rig.

**Comment by rahul27** [comment]
Made the changes. The tests work with the odd failure when the scene is null. 

Seems to be a race condition.

**Comment by NolaDonato** [comment]
Yes, Parth said he is going to look at it.

**Comment by rahul27** [comment]
This one can be merged.

**Pull request merged**
