### PR TITLE
Adding complex scene test

### PR DESCRIPTION
**Pull request by parthmehta209**
This also includes a script to build and run the test on a phone.

### CODE REVIEW

**Comment by parthmehta209** [comment]
@Vittalbabu you can try out the complex scene test on your machine if you want.

**Comment by liaxim** [comment]
Any chance this could be done without cloning the sample?

For example, run the complex scene app, parse the logcat output for the next 5 mins. The camera rig type can be overridden without recompiling the app (see GVRScene.getCameraRigType).

**Comment by liaxim** [comment]
@parthmehta209 @Vittalbabu What are we going to do with this pull request?

**Comment by parthmehta209** [comment]
I had written a script to parse logcat after running this test. If needed I
can abandon this change and make the script run the comolex scene app.

**Comment by liaxim** [comment]
I'd say it is preferable to use the stock gvr-complexscene app.

**Comment by parthmehta209** [comment]
Closing this pull request for now.

**Pull request closed without merging**
