### PR TITLE
Added lighting tests and valid test results

### PR DESCRIPTION
**Pull request by NolaDonato**
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by parthmehta209** [comment]
Depends on https://github.com/gearvrf/GearVRf-Tests/pull/12

**Comment by liaxim** [comment]
Needs rebase

**Comment by NolaDonato** [comment]
this is rebased and ready to go
directAndPointLightsIlluminate fails because specular color is not initialized
Several picking tests now fail after Rahul's bounding box change:
canPickObjectWithRay, testPickObjects no longer work

**Comment by liaxim** [comment]
So are the failing tests incorrect themselves or Rahul's change has issues?

**Comment by liaxim** [comment]
Conflicts now. Needs rebase.

**Comment by NolaDonato** [comment]
I think Rahul's change might have issues. It is returning different hit points than the test did before. I have rebased, can merge now.

**Comment by liaxim** [comment]
Needs rebase

**Comment by NolaDonato** [comment]
rebased

**Pull request merged**
