### PR TITLE
GVR-Physics initial tests

### PR DESCRIPTION
**Pull request by JulianaFigueira**
This adds a test project for the physics extension.

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: Juliana Figueira <juliana.f@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good. The tests pass. Will merge Monday morning.

**Comment by thomasflynn** [comment]
@NolaDonato is there anything else you want from these tests?  now's the time to ask.

**Comment by NolaDonato** [comment]
In RigidBodyAttributes.java createRigidBody() you don't have to remove the scene object at the end of the function. Each test is independent and starts with a fresh scene.

In meshWithTexture() you can do mWaiter.fail(e) instead of printing a stack trace to cause the test to fail when that exception occurs.

Can you do a test to verify that setEnable() works to enable and disable a specific rigid body?

**Comment by JulianaFigueira** [comment]
Yes, I added a new test for the setEnable() on a specific rigid body, when it is not enabled, gravity doesn't affect the RigidBody, but the SceneObject is still on the scene.
The other noted points were also addressed.

**Comment by liaxim** [comment]
Quite often simultaneousFreeFallTest fails with
```
java.lang.AssertionError: expected true
at net.jodah.concurrentunit.Waiter.fail(Waiter.java:205)
at net.jodah.concurrentunit.Waiter.assertTrue(Waiter.java:80)
at org.gearvrf.tester.PhysicsSimulationTest.runTest(PhysicsSimulationTest.java:189)
at org.gearvrf.tester.PhysicsSimulationTest.simultaneousFreeFallTest(PhysicsSimulationTest.java:117)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1959)
```

It is more likely a problem with the test framework. I can never get the tests to finish. There is always something that hangs; usually on waitForXFrames. Will look into the test framework issues.

**Comment by JulianaFigueira** [comment]
Some test really don't have the expected result yet, we are reviewing the Physics extension. But, I just found that adding an extra wait at the end of each one of them, avoids the hang.

**Comment by liaxim** [comment]
Planning to merge Wednesday morning. The hangs I will keep looking at as the time permits.

**Comment by liaxim** [comment]
@JulianaFigueira Your last commit completely removed the updateRigidBody test. Was that the intent? Because it is not clear from the commit message.

Merging anyway. We can always update.

**Comment by JulianaFigueira** [comment]
It is all right. Thank you @liaxim

**Comment by liaxim** [comment]
Question about simultaneousFreeFallTest; are the balls supposed to always stop on top of the boxes? Because most of the times they fall through and the test fails. On Note5 and S8 it fails 9 out 10 times for me.

**Comment by liaxim** [comment]
Looks to me like beginCallback.onSceneRendered is getting called more than the expected 1 time. Using the attached patch guarantees the sphere and the cubes will be added one time. The test started passing always for me.

[diff.txt](https://github.com/gearvrf/GearVRf-Tests/files/960011/diff.txt)

**Pull request merged**
